# Generated by Django 4.2.5 on 2023-09-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('did', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('dphno', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=20)),
                ('ill', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('dphno', models.BigIntegerField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
    ]
