# Generated by Django 4.2.5 on 2023-09-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_rename_dept_doctor_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dphno',
            new_name='pphno',
        ),
    ]
